version: '3.8'

services:
  postgres:
    container_name: maison-des-pains-db
    image: postgres:latest
    environment:
      POSTGRES_DB: maison_des_pains
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 